### ISSUE TITLE
build corebird master fail

### ISSUE THREAD

**Issue by aditiapratama** [baedert/corebird#281]
here's the `autogen.sh` log

```
autoreconf: Entering directory `.'
autoreconf: running: intltoolize --automake --copy
autoreconf: running: aclocal -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
autoreconf: running: /usr/bin/autoconf
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --no-force
examples/Makefile.am:16: warning: source file '$(top_srcdir)/src/resources.c' is in a subdirectory,
examples/Makefile.am:16: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
examples/Makefile.am:30: warning: source file '$(top_srcdir)/src/resources.c' is in a subdirectory,
examples/Makefile.am:30: but option 'subdir-objects' is disabled
examples/Makefile.am:21: warning: source file '$(top_srcdir)/src/resources.c' is in a subdirectory,
examples/Makefile.am:21: but option 'subdir-objects' is disabled
examples/Makefile.am:26: warning: source file '$(top_srcdir)/src/resources.c' is in a subdirectory,
examples/Makefile.am:26: but option 'subdir-objects' is disabled
examples/Makefile.am:12: warning: source file '$(top_srcdir)/src/resources.c' is in a subdirectory,
examples/Makefile.am:12: but option 'subdir-objects' is disabled
examples/Makefile.am:7: warning: source file '$(top_srcdir)/src/resources.c' is in a subdirectory,
examples/Makefile.am:7: but option 'subdir-objects' is disabled
tests/Makefile.am:65: warning: highlighting_SOURCES multiply defined in condition TRUE ...
tests/Makefile.am:61: ... 'highlighting_SOURCES' previously defined here
tests/Makefile.am:66: warning: highlighting_LDADD multiply defined in condition TRUE ...
tests/Makefile.am:62: ... 'highlighting_LDADD' previously defined here
tests/Makefile.am:67: warning: highlighting_VALAFLAGS multiply defined in condition TRUE ...
tests/Makefile.am:63: ... 'highlighting_VALAFLAGS' previously defined here
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking for valac... /usr/bin/valac
checking whether /usr/bin/valac is at least version 0.24... yes
checking whether NLS is requested... yes
checking for intltool >= 0.40... 0.50.2 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.20.1
checking for XML::Parser... ok
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CB... yes
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for msgmerge... (cached) /usr/bin/msgmerge
checking for ld used by gcc -std=gnu99... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating ui/Makefile
config.status: creating data/Makefile
config.status: creating data/org.baedert.corebird.desktop.in
config.status: creating data/symbolics/Makefile
config.status: creating examples/Makefile
config.status: creating assets/Makefile
config.status: creating assets/128x128/Makefile
config.status: creating assets/96x96/Makefile
config.status: creating assets/64x64/Makefile
config.status: creating assets/48x48/Makefile
config.status: creating assets/32x32/Makefile
config.status: creating assets/24x24/Makefile
config.status: creating assets/16x16/Makefile
config.status: creating po/Makefile.in
config.status: creating sql/Makefile
config.status: creating sql/accounts/Makefile
config.status: creating sql/init/Makefile
config.status: creating tests/Makefile
config.status: creating src/util/Config.vala
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

             Corebird  0.9
               Prefix: /usr
        Vala Compiler: /usr/bin/valac
           C Compiler: gcc -std=gnu99 -g -O2
            Debugging: no
       Video disabled: no
```

And here's the `make error` log

```
make[1]: Entering directory '/home/aditia/git/corebird/src'
list/ProgressEntry.vala:29.5-29.20: error: The name `activatable' does not exist in the context of `ProgressEntry'
    this.activatable = false;
    ^^^^^^^^^^^^^^^^
window/ComposeTweetWindow.vala:116.7-116.30: error: The name `activatable' does not exist in the context of `TweetListEntry?'
      answer_entry.activatable = false;
      ^^^^^^^^^^^^^^^^^^^^^^^^
list/ListListEntry.vala:174.5-174.20: error: The name `activatable' does not exist in the context of `ListListEntry'
    this.activatable = false;
    ^^^^^^^^^^^^^^^^
list/ListListEntry.vala:180.5-180.20: error: The name `activatable' does not exist in the context of `ListListEntry'
    this.activatable = true;
    ^^^^^^^^^^^^^^^^
list/FilterListEntry.vala:71.5-71.20: error: The name `activatable' does not exist in the context of `FilterListEntry'
    this.activatable = false;
    ^^^^^^^^^^^^^^^^
list/FilterListEntry.vala:77.5-77.20: error: The name `activatable' does not exist in the context of `FilterListEntry'
    this.activatable = true;
    ^^^^^^^^^^^^^^^^
SearchPage.vala:311.5-311.20: error: The name `activatable' does not exist in the context of `LoadMoreEntry'
    this.activatable = false;
    ^^^^^^^^^^^^^^^^
window/UserListDialog.vala:181.5-181.20: error: The name `activatable' does not exist in the context of `ListUserEntry'
    this.activatable = false;
    ^^^^^^^^^^^^^^^^
Corebird.vala:77.54-77.54: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.compose-tweet", {Settings.get_accel ("compose-tweet")});
                                                     ^
Corebird.vala:78.55-78.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.toggle-sidebar", {Settings.get_accel ("toggle-sidebar")});
                                                      ^
Corebird.vala:79.55-79.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(0)", {"<Alt>1"});
                                                      ^
Corebird.vala:80.55-80.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(1)", {"<Alt>2"});
                                                      ^
Corebird.vala:81.55-81.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(2)", {"<Alt>3"});
                                                      ^
Corebird.vala:82.55-82.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(3)", {"<Alt>4"});
                                                      ^
Corebird.vala:83.55-83.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(4)", {"<Alt>5"});
                                                      ^
Corebird.vala:84.55-84.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(5)", {"<Alt>6"});
                                                      ^
Corebird.vala:85.55-85.55: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.switch-page(6)", {"<Alt>7"});
                                                      ^
Corebird.vala:86.54-86.54: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("app.show-settings", {Settings.get_accel ("show-settings")});
                                                     ^
Corebird.vala:87.45-87.45: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("app.quit", {"<Control>Q"});
                                            ^
Corebird.vala:88.60-88.60: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.show-account-dialog", {Settings.get_accel ("show-account-dialog")});
                                                           ^
Corebird.vala:89.58-89.58: error: initializer list used for `string', which is neither array nor struct
    this.set_accels_for_action ("win.show-account-list", {Settings.get_accel ("show-account-list")});
                                                         ^
Compilation failed: 21 error(s), 0 warning(s)
Makefile:1101: recipe for target 'libcorebird_la_vala.stamp' failed
make[1]: *** [libcorebird_la_vala.stamp] Error 1
make[1]: Leaving directory '/home/aditia/git/corebird/src'
Makefile:431: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

I notice something wrong with vala, but not sure. Build on ubuntu 14.10 gnome shell 3.14.
Thanks.
